/**
 * Netlify build step. Does two things and nothing else — this site has no
 * bundler and does not need one.
 *
 *   1. Writes assets/js/env.js from the SUPABASE_URL and SUPABASE_ANON_KEY
 *      environment variables, falling back to the committed values so a
 *      fresh clone or a preview deploy still runs.
 *
 *   2. Generates _headers, including a Content Security Policy whose
 *      script-src is 'self' plus a SHA-256 hash for every inline <script>
 *      still present in the HTML. Hashing rather than 'unsafe-inline' means
 *      an injected <script> cannot execute, and generating the hashes here
 *      rather than by hand means editing a page cannot silently break it.
 *
 * Run locally with:  node tools/build-config.mjs
 */

import { createHash } from 'node:crypto';
import { readFile, writeFile, readdir } from 'node:fs/promises';
import { join, dirname, relative } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');

/* Fallbacks, used when the environment variables are not set. Both values
   are public: they identify the project, they do not grant access. */
const FALLBACK_URL = 'https://ftwkxuqqnbtuegabxxnj.supabase.co';
const FALLBACK_KEY =
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ0d2t4dXFxbmJ0dWVnYWJ4eG5qIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODg4Mjk4NzMsImV4cCI6MjEwNDQwNTg3M30.U-rq83swyVQkTwfvWdjX8-_tRdQd9RCoCMTkaJUpgR0';

const SUPABASE_URL = (process.env.SUPABASE_URL || FALLBACK_URL).replace(/\/+$/, '');
const SUPABASE_ANON_KEY = process.env.SUPABASE_ANON_KEY || FALLBACK_KEY;
const usingEnv = Boolean(process.env.SUPABASE_URL && process.env.SUPABASE_ANON_KEY);

/* ── Guard: a service-role key must never reach the client bundle ───── */
if (/service_role/.test(SUPABASE_ANON_KEY) || /^sb_secret_/.test(SUPABASE_ANON_KEY)) {
  console.error('\n✖ SUPABASE_ANON_KEY looks like a SERVICE ROLE key. Refusing to write it into a public file.\n');
  process.exit(1);
}

/* ── 1. env.js ──────────────────────────────────────────────────────── */

const envFile = `/**
 * GENERATED by tools/build-config.mjs — do not edit by hand.
 *
 * Both values are public by design: the anon/publishable key identifies the
 * project, it does not grant access. Every table is behind RLS and every Edge
 * Function re-reads the caller's profile before doing any work. The service
 * role key lives only in Supabase's Edge Function secrets.
 */
window.__NORTHLEAF_ENV__ = {
  SUPABASE_URL: ${JSON.stringify(SUPABASE_URL)},
  SUPABASE_ANON_KEY: ${JSON.stringify(SUPABASE_ANON_KEY)},
  BUILD: ${JSON.stringify(new Date().toISOString())}
};
`;

await writeFile(join(ROOT, 'assets/js/env.js'), envFile, 'utf8');

/* ── 2. Inline-script hashes ────────────────────────────────────────── */

async function htmlFiles(dir) {
  const found = [];
  for (const entry of await readdir(dir, { withFileTypes: true })) {
    if (entry.name.startsWith('.') || entry.name === 'node_modules') continue;
    const full = join(dir, entry.name);
    if (entry.isDirectory()) found.push(...(await htmlFiles(full)));
    else if (entry.name.endsWith('.html')) found.push(full);
  }
  return found;
}

const hashes = new Set();
const pages = await htmlFiles(ROOT);

for (const file of pages) {
  const html = await readFile(file, 'utf8');
  // Only <script> elements with no src attribute carry executable inline text.
  for (const match of html.matchAll(/<script(?![^>]*\ssrc=)[^>]*>([\s\S]*?)<\/script>/gi)) {
    const body = match[1];
    if (!body.trim()) continue;
    // The hash covers the element's exact text content, byte for byte.
    hashes.add(`'sha256-${createHash('sha256').update(body, 'utf8').digest('base64')}'`);
    console.log(`  inline script hashed in ${relative(ROOT, file)} (${body.length} bytes)`);
  }
}

/* ── 3. _headers ────────────────────────────────────────────────────── */

const csp = [
  "default-src 'self'",
  // Vendored Chart.js and supabase-js are same-origin, so no CDN is trusted.
  // Only the site's own scripts plus the exact inline blocks hashed above.
  `script-src 'self' ${[...hashes].join(' ')}`.trim(),
  // 'unsafe-inline' for styles only: the marketing pages carry per-page
  // <style> blocks and inline style attributes. Inline CSS cannot exfiltrate
  // data or execute code the way inline script can.
  "style-src 'self' 'unsafe-inline' https://fonts.googleapis.com",
  'font-src https://fonts.gstatic.com',
  // Amazon product thumbnails come from m.media-amazon.com.
  "img-src 'self' data: https://m.media-amazon.com https://images-na.ssl-images-amazon.com",
  // The Supabase project, and nothing else.
  `connect-src 'self' ${SUPABASE_URL} ${SUPABASE_URL.replace('https://', 'wss://')}`,
  "form-action 'self'",
  "frame-ancestors 'none'",
  "base-uri 'self'",
  "object-src 'none'",
  'upgrade-insecure-requests'
].join('; ');

const headersFile = `# GENERATED by tools/build-config.mjs — do not edit by hand.

/*
  Content-Security-Policy: ${csp}
  X-Frame-Options: DENY
  X-Content-Type-Options: nosniff
  Referrer-Policy: strict-origin-when-cross-origin
  Permissions-Policy: geolocation=(), microphone=(), camera=(), payment=(), interest-cohort=()
  Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
  Cross-Origin-Opener-Policy: same-origin

# The gated area is never cached by a shared proxy and never indexed.
/login.html
  Cache-Control: no-store
  X-Robots-Tag: noindex, nofollow, noarchive

/dashboard/*
  Cache-Control: no-store
  X-Robots-Tag: noindex, nofollow, noarchive

# env.js is regenerated on every build; never let a browser pin an old one.
/assets/js/env.js
  Cache-Control: no-store

# Vendored libraries are pinned by version and safe to cache hard.
/assets/vendor/*
  Cache-Control: public, max-age=31536000, immutable
`;

await writeFile(join(ROOT, '_headers'), headersFile, 'utf8');

console.log(`\n✔ env.js written (${usingEnv ? 'from environment variables' : 'from committed fallback'})`);
console.log(`  SUPABASE_URL = ${SUPABASE_URL}`);
console.log(`✔ _headers written with ${hashes.size} inline-script hash${hashes.size === 1 ? '' : 'es'}`);
console.log(`  scanned ${pages.length} HTML files\n`);
